import "./../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <nav className="primary bg-backgroundSecundary h-36 shadow-md">
        <div className="max-w-6xl mx-auto justify-between">
          <p>
            Wagner
            <br />
            Caetano{" "}
          </p>
        </div>
        <div className="inline-flex gap-6">
          <Link href={"/about"}>
            <p>About</p>
          </Link>
          <Link href={"/portfolio"}>
            <p>Portfolio</p>
          </Link>
          <Link href={"/skills"}>
            <p>Skills</p>
          </Link>
          <Link href={"/contact"}>
            <p>Contact</p>
          </Link>
          <Link className="border rounded-md text-center border-primary" href={"/download/resume"}>
            <p>Download Resume</p>
          </Link>
        </div>
      </nav>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
