export const keywordsDeveloper = [
  'Brazilian Software Engineer',
  'Brazilian',
  'Software Engineer',
  'Software Developer',
  'Next.js Software Engineer',
  'Angular Software Engineer',
  'React Software Engineer',
  'Full-stack Developer',
  'Backend Developer',
  'Frontend Developer',
  'Java Developer',
  'Node.js Developer',
  'Web Developer',
  'Software Design',
  'Software Architecture',
  'Agile Methodologies',
  'Git',
  'Web Development',
  'Cutting-edge Projects',
  'Diverse Teams',
  'Professional Growth',
  'Competitive Salary',
  'Flexible Work Schedule',
  'Remote Work',
];
